name: CI

on:
  push:
    branches:
      -'LR**'
  pull_request:
    branches :
      - main 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: cd SpaceBattle.Lib && cd SpaceBattle.Tests && dotnet restore SpaceBattle.Lib.Tests

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-coverage
          dotnet tool install coverlet.console
      - name: Build
        run: cd SpaceBattle.Lib && cd SpaceBattle.Tests && dotnet build
      - name: Coverage and test
        run: cd SpaceBattle.Lib && cd SpaceBattle.Tests && dotnet coverlet SpaceBattle.Lib.Tests/bin/Debug/net7.0/SpaceBattle.Lib.Tests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
